/**
 * Settings screen.
 *
 * The controls are NOT hand-written: they're generated by reading the theme
 * pack's tokenSchema. Adding a token with its schema entry makes its control
 * appear on its own, without touching this file. That's the whole point of
 * tokenSchema existing.
 */
import { App, PluginSettingTab, Setting } from "obsidian";
import type PressmarkPlugin from "./main";
import type { Resolved, TokenDef } from "./theme";
import { t, language } from "./i18n";
import { DEFAULT_SETTINGS, type Settings } from "./config";

export { DEFAULT_SETTINGS };
export type { Settings };
import { resolve } from "./locale";

const GROUP_ORDER = ["footer", "palette", "typography", "cover"];

/**
 * Groups come from the tokenSchema as plain identifiers ("palette"). The
 * known ones get translated; one of the user's own theme pack shows up as-is,
 * which beats hiding it.
 */
function groupName(g: string): string {
  const known = ["footer", "palette", "typography", "cover", "other"] as const;
  if ((known as readonly string[]).includes(g)) {
    return t(`group.${g}` as Parameters<typeof t>[0]);
  }
  return g.charAt(0).toUpperCase() + g.slice(1);
}

export class SettingsTab extends PluginSettingTab {
  constructor(
    app: App,
    private plugin: PressmarkPlugin,
  ) {
    super(app, plugin);
  }

  override display(): void {
    const { containerEl } = this;
    containerEl.empty();

    new Setting(containerEl).setName(t("set.export")).setHeading();

    void this.generalSection(containerEl);
  }

  private async generalSection(c: HTMLElement): Promise<void> {
    const ids = await this.plugin.availableThemes();

    new Setting(c)
      .setName(t("set.themePack"))
      .setDesc(t("set.themePackDesc"))
      .addDropdown((d) => {
        for (const id of ids) d.addOption(id, id);
        d.setValue(this.plugin.settings.theme).onChange(async (v) => {
          this.plugin.settings.theme = v;
          await this.plugin.saveSettings();
          this.display();
        });
      });

    new Setting(c)
      .setName(t("set.openWhenDone"))
      .addToggle((c) =>
        c.setValue(this.plugin.settings.openWhenDone).onChange(async (v) => {
          this.plugin.settings.openWhenDone = v;
          await this.plugin.saveSettings();
        }),
      );

    new Setting(c)
      .setName(t("set.outputFolder"))
      .setDesc(t("set.outputFolderDesc"))
      .addText((c) =>
        c
          .setPlaceholder("exportados/")
          .setValue(this.plugin.settings.outputFolder)
          .onChange(async (v) => {
            this.plugin.settings.outputFolder = v.trim();
            await this.plugin.saveSettings();
          }),
      );

    let theme: Resolved;
    try {
      theme = await this.plugin.loadTheme(this.plugin.settings.theme);
    } catch (e) {
      new Setting(c).setName(t("set.loadError")).setDesc(String(e));
      return;
    }
    this.editableSection(c, theme, "tokens");
    this.editableSection(c, theme, "vars");
  }

  /**
   * This is where the form draws itself.
   *
   * Serves both tokens and vars without duplicating anything: the two layers
   * declare their schema the same way (tokenSchema / varSchema), so there's
   * just one generator.
   */
  private editableSection(c: HTMLElement, theme: Resolved, layer: "tokens" | "vars"): void {
    const schema = (layer === "tokens" ? theme.tokenSchema : theme.varSchema) ?? {};
    const values = ((layer === "tokens" ? theme.tokens : theme.vars) ?? {}) as Record<string, unknown>;
    const names = Object.keys(schema).filter((k) => k in values);
    if (names.length === 0) return;

    new Setting(c)
      .setName(t(layer === "tokens" ? "set.customization" : "set.texts"))
      .setHeading();
    c.createEl("p", {
      text:
        layer === "tokens"
          ? t("set.customizationDesc", { id: theme.id })
          : t("set.textsDesc"),
      cls: "setting-item-description",
    });

    const byGroup = new Map<string, string[]>();
    for (const n of names) {
      const g = schema[n]!.group ?? "other";
      byGroup.set(g, [...(byGroup.get(g) ?? []), n]);
    }

    const groups = [...byGroup.keys()].sort((a, b) => {
      const ia = GROUP_ORDER.indexOf(a);
      const ib = GROUP_ORDER.indexOf(b);
      return (ia < 0 ? 99 : ia) - (ib < 0 ? 99 : ib) || a.localeCompare(b);
    });

    for (const g of groups) {
      if (groups.length > 1) new Setting(c).setName(groupName(g)).setHeading();
      for (const n of byGroup.get(g)!) {
        this.renderControl(c, theme, layer, n, schema[n]!, resolve(values[n] as never, language()));
      }
    }

    new Setting(c).addButton((b) =>
      b
        .setButtonText(t("set.resetAll"))
        .setWarning()
        .onClick(async () => {
          delete this.overrideMap(layer)[theme.id];
          await this.plugin.saveSettings();
          this.display();
        }),
    );
  }

  private overrideMap(layer: "tokens" | "vars"): Record<string, Record<string, string>> {
    return layer === "tokens" ? this.plugin.settings.overrides : this.plugin.settings.overridesVars;
  }

  private renderControl(
    c: HTMLElement,
    theme: Resolved,
    layer: "tokens" | "vars",
    name: string,
    def: TokenDef,
    themeValue: string,
  ): void {
    const overrides = this.overrideMap(layer)[theme.id] ?? {};
    const current = overrides[name] ?? themeValue;
    const overridden = name in overrides;

    const s = new Setting(c).setName(resolve(def.label, language()));
    const desc = resolve(def.description, language());
    if (desc) s.setDesc(desc);
    if (overridden) s.nameEl.createSpan({ text: " ·", cls: "mod-warning" });

    const save = async (v: string) => {
      const map = this.overrideMap(layer);
      const o = map[theme.id] ?? {};
      if (v === themeValue) delete o[name];
      else o[name] = v;
      if (Object.keys(o).length === 0) delete map[theme.id];
      else map[theme.id] = o;
      await this.plugin.saveSettings();
    };

    // The token's type decides the control. Without this switch there would
    // be thirteen hand-written controls to touch again with every new token.
    switch (def.type) {
      case "color":
        s.addColorPicker((p) => p.setValue(current).onChange(save));
        break;
      case "number":
        s.addText((c) =>
          c.setValue(current).setPlaceholder(themeValue).onChange(save).inputEl.setAttr("type", "number"),
        );
        break;
      default:
        s.addText((c) => c.setValue(current).setPlaceholder(themeValue).onChange(save));
    }

    if (overridden) {
      s.addExtraButton((b) =>
        b
          .setIcon("rotate-ccw")
          .setTooltip(t("set.backToThemeValue"))
          .onClick(() => {
            void save(themeValue).then(() => this.display());
          }),
      );
    }
  }
}
